FeedBackDemo/Controllers/FeedBackController.cs
using FeedBackDemo.Models;
using FeedBackDemo.Models.ViewModels;
using FeedBackDemo.Repo;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeedBackDemo.Controllers
{
    [Authorize]
    public class FeedBackController : Controller
    {
        // GET: FeedBack
        public ActionResult Index()
        {
            FeedBackVM fb = new FeedBackVM();
            using (var context= new ApplicationDbContext())
            {
                FeedBackRepo feedBack = new FeedBackRepo(context);
           
              
                feedBack.GetAllPosts(1, fb);
            }
           
            return View(fb);
        }

        [HttpPost]
        public ActionResult Index(FeedBackVM fb)
        {
            using (var context = new ApplicationDbContext())
            {
                FeedBackRepo feedBack = new FeedBackRepo(context);
                //Reset page count
                if (fb.HiddenItemPerPage != fb.ItemPerPage)
                {
                    fb.page = 1;

                }
                else
                {
                    fb.page = fb.page;

                }
                fb.HiddenItemPerPage = fb.ItemPerPage;

                feedBack.GetAllPosts((int)fb.page, fb);
            }

            return View(fb);
        }

        public JsonResult Vote(Vote vote)
        {
            using (var context = new ApplicationDbContext())
            {
                FeedBackRepo feedBack = new FeedBackRepo(context);
                var userId = User.Identity.GetUserId();
                if (context.Votes.Any(x => x.CommentId == vote.CommentId && x.CreatedBy== userId))
                {
                    var type = context.Votes.FirstOrDefault(x => x.CommentId == vote.CommentId && x.CreatedBy== userId);
                    if (type.Type != vote.Type)
                    {
                        type.Type = vote.Type;
                        vote.CreateDate = DateTime.UtcNow;
                     
                        context.SaveChanges();

                        var voteCount = feedBack.CountVote(vote.CommentId);
                        feedBack.UpdateCommentCount(vote.CommentId, voteCount[0], voteCount[1]);

                        return Json(new { like = voteCount[0], dislike = voteCount[1] }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var voteCount = feedBack.CountVote(vote.CommentId);
                        feedBack.UpdateCommentCount(vote.CommentId, voteCount[0], voteCount[1]);
                        return Json(new { like = voteCount[0], dislike = voteCount[1] }, JsonRequestBehavior.AllowGet);
                    }


                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        vote.CreatedBy = User.Identity.GetUserId();
                        vote.CreateDate = DateTime.UtcNow;
                       

                        context.Votes.Add(vote);
                        context.SaveChanges();
                        var voteCount = feedBack.CountVote(vote.CommentId);

                        feedBack.UpdateCommentCount(vote.CommentId, voteCount[0], voteCount[1]);

                        return Json(new { like = voteCount[0], dislike = voteCount[1] }, JsonRequestBehavior.AllowGet);
                    }
                }

            }


            return Json(false);
        }


        // GET: FeedBack
        public ActionResult Index2()
        {
            FeedBackVM fb = new FeedBackVM();
            using (var context = new ApplicationDbContext())
            {
                FeedBackRepo feedBack = new FeedBackRepo(context);


                feedBack.GetAllPost(1, fb);
            }

            return View(fb);
        }

        [HttpPost]
        public ActionResult Index2(FeedBackVM fb)
        {
            using (var context = new ApplicationDbContext())
            {
                FeedBackRepo feedBack = new FeedBackRepo(context);
                //Reset page count
                if (fb.HiddenItemPerPage != fb.ItemPerPage)
                {
                    fb.page = 1;

                }
                else
                {
                    fb.page = fb.page;

                }
                fb.HiddenItemPerPage = fb.ItemPerPage;

                feedBack.GetAllPost((int)fb.page, fb);
            }

            return View(fb);
        }


    }
}

FeedBackDemo/Views/FeedBack/Index.cshtml
@model FeedBackDemo.Models.ViewModels.FeedBackVM
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-body">

    @using (Html.BeginForm("Index", "FeedBack", FormMethod.Post, new { id = "searchForm" }))
    {


        <div class="form-body" style="margin-bottom:15px;margin-right:13px;">
            <div class="row">

                @Html.HiddenFor(x => x.page)
                <input type="hidden" name="HiddenItemPerPage" value="@Model.HiddenItemPerPage" />
                <input type="hidden" name="ItemPerPage" value="@Model.ItemPerPage" />
              

            </div>



            <div class="row" style="margin-top:10px;">





                <div class="col-md-8">

                </div>
                <div class="col-md-4">
                    <input id="myInput" class="form-control input-sm" type="text" placeholder="Search Posts.." style="margin-bottom:10px;">
                </div>
                <div class="col-md-12">
                   
                    <div class="table-responsive" style="font-size: 12px;">
                        <table id="postTbl" class="table table-sm table-bordered table-striped table-hover datatable" style="white-space:nowrap">

                            <tbody>
                                @foreach (var item in Model.PostList)
                                {
                                    <tr id="@item.Id" style="color:white;background-color:#22796e;font-weight:bold;" class="">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Title)
                                        </td>
                                        <td>
                                            @item.User.UserName
                                        </td>
                                        <td>
                                            @item.CreateDate.ToLocalTime()
                                        </td>
                                        <td>
                                            @if (@item.PostComments.Count > 1)
                                            {
                                                @item.PostComments.Count @Html.Raw(" Comments")
                                            }
                                            else
                                            {
                                                @item.PostComments.Count @Html.Raw(" Comment")
                                            }
                                        </td>
                                    </tr>
                                    foreach (var pp in item.PostComments)
                                    {
                                        <tr id="@pp.Id">
                                            <td style="padding-left:10px;">
                                                @pp.Description
                                            </td>
                                            <td>
                                                @pp.User.UserName
                                            </td>
                                            <td>
                                                @pp.CreateDate.ToLocalTime()
                                            </td>
                                            <td>
                                                <span class="vote" data-type="1" style="color:green"><i class="fa fa-angle-up"></i> <span id="likeVote_@pp.Id"> @pp.VoteList.Count(x => x.Type == 1) </span> </span>
                                                <span class="vote" data-type="2" style="color:red;margin-left:5px"><i class="fa fa-angle-down"></i> <span id="dislikeVote_@pp.Id">@pp.VoteList.Count(x => x.Type == 2) </span> </span>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>

                        </table>

                    </div>


                </div>
            </div>

            <div class="row">

                <div class="col-md-6 ">
                    <!-- pager -->
                    @if (Model.pager.EndPage > 1)
                    {
                        <ul class="pagination pull-left" id="results">
                            @if (Model.pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@Model.pager.StartPage">First</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@(Model.pager.CurrentPage-1)">Previous</a>
                                </li>
                            }

                            @for (var page = Model.pager.StartPage; page <= Model.pager.EndPage; page++)
                            {
                                <li class="page-item @(page == Model.pager.CurrentPage ? "active" : "")">
                                    <a class="page-link" href="#" id="@page">@page</a>
                                </li>
                            }

                            @if (Model.pager.CurrentPage < Model.pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@(Model.pager.CurrentPage + 1)">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@(Model.pager.TotalPages)">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </div>
           
            <div class="col-md-6 pull-left">
               
                <h3 class="text-muted">Total @Model.TotalPost Posts</h3>
            </div>
            </div>

        </div>




    }




</div>



@section scripts{


    <script type="text/javascript">
        $(document).ready(function () {

        

        
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#postTbl tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });


 


            //Pagination
            $('#results li a').click(function (e) {

                var id = e.currentTarget.id;

                 $('#page').val(id);


            $('#searchForm').submit();

            return false;
            });

            $('.vote').click(function () {
                let type = $(this).data('type');
                //alert(type);
                var trid = $(this).closest('tr').attr('id');

                $.ajax({
                    type: 'Get',
                    url: "/FeedBack/Vote",
                    contentType: "application/json; charset=utf-8",
                    data: { "CommentId": trid, "Type": type },
                    datatype: 'Json',
                    success: function (data) {

                        $('#likeVote_' + trid).text(data.like);
                        $('#dislikeVote_' + trid).text(data.dislike);

                    }
                });
            })


        



        });



    </script>
}

FeedBackDemo/Views/FeedBack/Index2.cshtml
@model FeedBackDemo.Models.ViewModels.FeedBackVM
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card-body">

    @using (Html.BeginForm("Index2", "FeedBack", FormMethod.Post, new { id = "searchForm" }))
    {


        <div class="form-body" style="margin-bottom:15px;margin-right:13px;">
            <div class="row">

                @Html.HiddenFor(x => x.page)
                <input type="hidden" name="HiddenItemPerPage" value="@Model.HiddenItemPerPage" />
                <input type="hidden" name="ItemPerPage" value="@Model.ItemPerPage" />


            </div>



            <div class="row" style="margin-top:10px;">





                <div class="col-md-8">

                </div>
                <div class="col-md-4">
                    <input id="myInput" class="form-control input-sm" type="text" placeholder="Search Posts.." style="margin-bottom:10px;">
                </div>
                <div class="col-md-12">

                    <div class="table-responsive" style="font-size: 12px;">
                        <table id="postTbl" class="table table-sm table-bordered table-striped table-hover datatable" style="white-space:nowrap">

                            <tbody>
                                @foreach (var item in Model.PostList)
                                {
                                    <tr id="@item.Id" style="color:white;background-color:#22796e;font-weight:bold;" class="">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Title)
                                        </td>
                                        <td>
                                            @item.User.UserName
                                        </td>
                                        <td>
                                            @item.CreateDate.ToLocalTime()
                                        </td>
                                        <td>
                                            @if (@item.PostComments.Count > 1)
                                            {
                                                @item.PostComments.Count @Html.Raw(" Comments")
                                            }
                                            else
                                            {
                                                @item.PostComments.Count @Html.Raw(" Comment")
                                            }
                                        </td>
                                    </tr>
                                    foreach (var pp in item.PostComments)
                                    {
                                        <tr id="@pp.Id">
                                            <td style="padding-left:10px;">
                                                @pp.Description
                                            </td>
                                            <td>
                                                @pp.User.UserName
                                            </td>
                                            <td>
                                                @pp.CreateDate.ToLocalTime()
                                            </td>
                                            <td>
                                                <span class="vote" data-type="1" style="color:green"><i class="fa fa-angle-up"></i> <span id="likeVote_@pp.Id"> @pp.LikeCount </span> </span>
                                                <span class="vote" data-type="2" style="color:red;margin-left:5px"><i class="fa fa-angle-down"></i> <span id="dislikeVote_@pp.Id">@pp.DisLikeCount </span> </span>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>

                        </table>

                    </div>


                </div>
            </div>

            <div class="row">

                <div class="col-md-6 ">
                    <!-- pager -->
                    @if (Model.pager.EndPage > 1)
                    {
                        <ul class="pagination pull-left" id="results">
                            @if (Model.pager.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@Model.pager.StartPage">First</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@(Model.pager.CurrentPage-1)">Previous</a>
                                </li>
                            }

                            @for (var page = Model.pager.StartPage; page <= Model.pager.EndPage; page++)
                            {
                                <li class="page-item @(page == Model.pager.CurrentPage ? "active" : "")">
                                    <a class="page-link" href="#" id="@page">@page</a>
                                </li>
                            }

                            @if (Model.pager.CurrentPage < Model.pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@(Model.pager.CurrentPage + 1)">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#" id="@(Model.pager.TotalPages)">Last</a>
                                </li>
                            }
                        </ul>
                    }
                </div>

                <div class="col-md-6 pull-left">

                    <h3 class="text-muted">Total @Model.TotalPost Posts</h3>
                </div>
            </div>

        </div>




    }




</div>



@section scripts{


    <script type="text/javascript">
        $(document).ready(function () {




            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#postTbl tbody tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });





            //Pagination
            $('#results li a').click(function (e) {

                var id = e.currentTarget.id;

                 $('#page').val(id);


            $('#searchForm').submit();

            return false;
            });

            $('.vote').click(function () {
                let type = $(this).data('type');
                //alert(type);
                var trid = $(this).closest('tr').attr('id');

                $.ajax({
                    type: 'Get',
                    url: "/FeedBack/Vote",
                    contentType: "application/json; charset=utf-8",
                    data: { "CommentId": trid, "Type": type },
                    datatype: 'Json',
                    success: function (data) {

                        $('#likeVote_' + trid).text(data.like);
                        $('#dislikeVote_' + trid).text(data.dislike);

                    }
                });
            })






        });



    </script>
}